# Introduction to Pandas

While working on this tutorial, I stumbled upon [this](https://nbviewer.jupyter.org/github/groverpr/learn_python_libraries/blob/master/pandas/pandas_cheatsheet.ipynb#Common-dataframe-functionality) fantastic guide. I'm still working on my own guide because I focus on a couple of things the other guide goes over quickly, but the other tutorial is much more comprehensive.

By the end of this tutorial, you will be able to:
- Explain what pandas is and where it is useful
- Change and create directories using the os package
- Explore the structure of a dataframe
- Perform summary statistics on a dataframe
- Generate new variables
- Create cross-tabulations and pivot tables
- Merge and append data

<a id='toc'></a>
## Table of Contents

- [Overview](#overview)
- [Setting the environment](#setenv)
- [Exploring the Structure of Your Dataframe](#exploredf)
- [Sorting and Subsetting](#sort)
- [Manipulating Data Types](#datatype)
- [Generating Variables](#gen)
- [Summary Statistics and Tabulation](#tab)
- [Concatenating Dataframes](#concat)

<a id='overview'></a>
## Overview
([Back to Table of Contents](#toc))

### What is pandas?

pandas is a Python package that makes it easy to clean, manipulate, and perform data analysis on structured data.

The package was developed by Wes McKinney in 2012. Before pandas, dealing with dataframe structures was difficult, and certainly not as easy or flexible as they are in R or statistical software like Stata. With pandas, Python is certainly a reasonable alternative to paid software and even other open-source software like R. This is especially true if your analysis mixes other programming tasks like webscraping.

### Getting Help

Before getting started with pandas, you should definitely read their [documentation](https://pandas.pydata.org/pandas-docs/stable/) and the developers' own [tutorial](https://pandas.pydata.org/pandas-docs/stable/10min.html), titled Ten Minutes to Pandas.

Also, note that any time you need help, you can use **[package or function name]?** in Jupyter Notebook to get more information about a package that has already been imported. You can also see the underlying code by using double question marks.

In [1]:
import pandas as pd
pd.read_csv?

<a id='setenv'></a>
## Setting the Environment
([Back to Table of Contents](#toc))

I use the top of a script to import modules I will be using, to set names I want to call throughout the project, load my preferences, and to change to my current working directory.

In [2]:
# import modules
import os
import numpy as np
import pandas as pd
import seaborn as sns

So, if you've started a project, you should have already created a folder for and started this notebook file from within that new folder. In which case, you should be in the right directory. But just some tips on how to check this:

In [3]:
# Set working directory if necessary
os.getcwd() # gets current working directory
os.makedirs("test") # creates a new directory
print(os.listdir()) # checks all files in current directory
os.removedirs("test") # erases the directory

['.ipynb_checkpoints', '0. Executing Your First Python Script.ipynb', '1. Introduction to Python.ipynb', '2. The Basics of Programming (with Python).ipynb', '3. Intermediate Concepts in Python.ipynb', '4. Introduction to Data Analysis in Python (with pandas).ipynb', 'README.md', 'Screenshots', 'test']

**Tip:** I could not remember all of the above commands off the top of my head. Rather, I typed something like "os.make" and pressed tab, and Jupyter listed all of the modules in **os** that began with "make" (there is actually just one and Jupyter went ahead and completed it for me once I hit tab).

Finally, you can load in your data. pandas has a variety of methods to load data from a variety of different data types. I've included them below (but commented out). If you decide to use them, remember to look at the documentation or simply type the method followed by a question mark (e.g., **read_csv?**) into the console to see what kind of parameters it takes (e.g., you can pass an argument to ignore the first *n* lines of a CSV). 

We will not be loading in data from a CSV or Excel spreadsheet here. For this tutorial, we will actually use a dataset that we can import from a package.

Data scientists often use two datasets, *iris* and *mtcars*, to demonstrate various data analysis tools. While at least one of these is readily available in R and Stata, Python and pandas do not have either of these datasets available out of the box. Fortunately, data science packages including **seaborn** do have these readily available.

In [4]:
# Load data
#pd.read_csv("test.csv")
#pd.read_excel("test.xls")
#pd.read_stata("test.dta")
iris = sns.load_dataset('iris') # this comes from seaborn (see the modules we imported above)

In [5]:
# Check to make sure that *iris* was imported as a pandas DataFrame object
type(iris)

pandas.core.frame.DataFrame

<a id='exploredf'></a>
## Exploring the Structure of Your Dataframe
([Back to Table of Contents](#toc))

In [6]:
# Basic information about dataframe
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
sepal_length    150 non-null float64
sepal_width     150 non-null float64
petal_length    150 non-null float64
petal_width     150 non-null float64
species         150 non-null object
dtypes: float64(4), object(1)
memory usage: 5.9+ KB

In [7]:
# Get column names
iris.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

Did you notice that there was no parentheses after **columns**? Recall from earlier tutorials that class objects have both data attributes and method attributes. If a parentheses follows a name, that signals that we are dealing with a method attribute. If not, it is a data attribute (this was the difference between mydog.bark() and mydog.name, if you can recall back to our earlier tutorial on object-oriented programming).

In [8]:
# Return number of observations
len(iris.index)

150

In [9]:
# Get number of rows and columns in dataframe
iris.shape

(150, 5)

In [10]:
# Get datatypes of each column
iris.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [11]:
# By default, get first five observations in dataframe
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

**Note:** Remember that *iris* here is a pandas DataFrame object and therefore has access to all methods of the pandas class DataFrame. Each method takes a series of parameters. You'll notice above that I didn't pass any arguments to *head*; however, *head* has a series of defaults it uses if a user does not pass it any arguments.

For all  methods I access throughout this tutorial, I rely heavily on the defaults. You should type **[methodname]?** into Jupyter or read the documentation to figure out what parameters each method takes.

<a id='sort'></a>
## Sorting and Subsetting
([Back to Table of Contents](#toc))

In [12]:
# Sorting data by a specific column
iris.sort_values('sepal_length')

     sepal_length  sepal_width  petal_length  petal_width     species
13            4.3          3.0           1.1          0.1      setosa
42            4.4          3.2           1.3          0.2      setosa
38            4.4          3.0           1.3          0.2      setosa
8             4.4          2.9           1.4          0.2      setosa
41            4.5          2.3           1.3          0.3      setosa
22            4.6          3.6           1.0          0.2      setosa
3             4.6          3.1           1.5          0.2      setosa
6             4.6          3.4           1.4          0.3      setosa
47            4.6          3.2           1.4          0.2      setosa
2             4.7          3.2           1.3          0.2      setosa
29            4.7          3.2           1.6          0.2      setosa
12            4.8          3.0           1.4          0.1      setosa
45            4.8          3.0           1.4          0.3      setosa
24            4.8          3.4           1.9          0.2      setosa
11            4.8          3.4           1.6          0.2      setosa
30            4.8          3.1           1.6          0.2      setosa
57            4.9          2.4           3.3          1.0  versicolor
106           4.9          2.5           4.5          1.7   virginica
34            4.9          3.1           1.5          0.2      setosa
9             4.9          3.1           1.5          0.1      setosa
37            4.9          3.6           1.4          0.1      setosa
1             4.9          3.0           1.4          0.2      setosa
40            5.0          3.5           1.3          0.3      setosa
26            5.0          3.4           1.6          0.4      setosa
49            5.0          3.3           1.4          0.2      setosa
35            5.0          3.2           1.2          0.2      setosa
43            5.0          3.5           1.6          0.6      setosa
60            5.0          2.0           3.5          1.0  versicolor
7             5.0          3.4           1.5          0.2      setosa
93            5.0          2.3           3.3          1.0  versicolor
..            ...          ...           ...          ...         ...
58            6.6          2.9           4.6          1.3  versicolor
75            6.6          3.0           4.4          1.4  versicolor
86            6.7          3.1           4.7          1.5  versicolor
140           6.7          3.1           5.6          2.4   virginica
108           6.7          2.5           5.8          1.8   virginica
77            6.7          3.0           5.0          1.7  versicolor
65            6.7          3.1           4.4          1.4  versicolor
144           6.7          3.3           5.7          2.5   virginica
145           6.7          3.0           5.2          2.3   virginica
124           6.7          3.3           5.7          2.1   virginica
143           6.8          3.2           5.9          2.3   virginica
76            6.8          2.8           4.8          1.4  versicolor
112           6.8          3.0           5.5          2.1   virginica
139           6.9          3.1           5.4          2.1   virginica
141           6.9          3.1           5.1          2.3   virginica
52            6.9          3.1           4.9          1.5  versicolor
120           6.9          3.2           5.7          2.3   virginica
50            7.0          3.2           4.7          1.4  versicolor
102           7.1          3.0           5.9          2.1   virginica
129           7.2          3.0           5.8          1.6   virginica
125           7.2          3.2           6.0          1.8   virginica
109           7.2          3.6           6.1          2.5   virginica
107           7.3          2.9           6.3          1.8   virginica
130           7.4          2.8           6.1          1.9   virginica
105           7.6          3.0           6.6          2.1   virginica
122           7.7          2.8           6.7          2.0   virginica
118           7.7          2.6           6.9          2.3   virginica
117           7.7          3.8           6.7          2.2   virginica
135           7.7          3.0           6.1          2.3   virginica
131           7.9          3.8           6.4          2.0   virginica

[150 rows x 5 columns]

In [13]:
# Note that iris has not changed
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [14]:
# The two commands below are equivalent and would change iris permanently
iris = iris.sort_values('sepal_length')
iris.sort_values('sepal_length', inplace=True) # more on this one below
iris.head()

    sepal_length  sepal_width  petal_length  petal_width species
13           4.3          3.0           1.1          0.1  setosa
42           4.4          3.2           1.3          0.2  setosa
38           4.4          3.0           1.3          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
41           4.5          2.3           1.3          0.3  setosa

In [15]:
# Selecting a single columns
iris['sepal_length'].head()

13    4.3
42    4.4
38    4.4
8     4.4
41    4.5
Name: sepal_length, dtype: float64

In [16]:
# Selecting multiple columns
iris[['sepal_length', 'sepal_width']].head()

    sepal_length  sepal_width
13           4.3          3.0
42           4.4          3.2
38           4.4          3.0
8            4.4          2.9
41           4.5          2.3

In [17]:
# Get unique values of column
iris['species'].unique()

array(['setosa', 'virginica', 'versicolor'], dtype=object)

In [18]:
# Filtering the entire dataset based on specific columns
iris[iris['species']=="versicolor"] # Get the part of iris where the column "species" takes the value "versicolor"

    sepal_length  sepal_width  petal_length  petal_width     species
57           4.9          2.4           3.3          1.0  versicolor
60           5.0          2.0           3.5          1.0  versicolor
93           5.0          2.3           3.3          1.0  versicolor
98           5.1          2.5           3.0          1.1  versicolor
59           5.2          2.7           3.9          1.4  versicolor
84           5.4          3.0           4.5          1.5  versicolor
89           5.5          2.5           4.0          1.3  versicolor
80           5.5          2.4           3.8          1.1  versicolor
81           5.5          2.4           3.7          1.0  versicolor
90           5.5          2.6           4.4          1.2  versicolor
53           5.5          2.3           4.0          1.3  versicolor
64           5.6          2.9           3.6          1.3  versicolor
88           5.6          3.0           4.1          1.3  versicolor
66           5.6          3.0           4.5          1.5  versicolor
69           5.6          2.5           3.9          1.1  versicolor
94           5.6          2.7           4.2          1.3  versicolor
55           5.7          2.8           4.5          1.3  versicolor
96           5.7          2.9           4.2          1.3  versicolor
79           5.7          2.6           3.5          1.0  versicolor
99           5.7          2.8           4.1          1.3  versicolor
95           5.7          3.0           4.2          1.2  versicolor
82           5.8          2.7           3.9          1.2  versicolor
92           5.8          2.6           4.0          1.2  versicolor
67           5.8          2.7           4.1          1.0  versicolor
61           5.9          3.0           4.2          1.5  versicolor
70           5.9          3.2           4.8          1.8  versicolor
78           6.0          2.9           4.5          1.5  versicolor
83           6.0          2.7           5.1          1.6  versicolor
85           6.0          3.4           4.5          1.6  versicolor
62           6.0          2.2           4.0          1.0  versicolor
91           6.1          3.0           4.6          1.4  versicolor
63           6.1          2.9           4.7          1.4  versicolor
73           6.1          2.8           4.7          1.2  versicolor
71           6.1          2.8           4.0          1.3  versicolor
68           6.2          2.2           4.5          1.5  versicolor
97           6.2          2.9           4.3          1.3  versicolor
87           6.3          2.3           4.4          1.3  versicolor
56           6.3          3.3           4.7          1.6  versicolor
72           6.3          2.5           4.9          1.5  versicolor
51           6.4          3.2           4.5          1.5  versicolor
74           6.4          2.9           4.3          1.3  versicolor
54           6.5          2.8           4.6          1.5  versicolor
75           6.6          3.0           4.4          1.4  versicolor
58           6.6          2.9           4.6          1.3  versicolor
65           6.7          3.1           4.4          1.4  versicolor
86           6.7          3.1           4.7          1.5  versicolor
77           6.7          3.0           5.0          1.7  versicolor
76           6.8          2.8           4.8          1.4  versicolor
52           6.9          3.1           4.9          1.5  versicolor
50           7.0          3.2           4.7          1.4  versicolor

Note that the above does not change the iris dataset permanently. To do that, you have to set iris equal to the expression on the right-hand side. Alternatively, many methods also have a parameter called *inplace* that will allow you to permanently change the dataset without setting iris equal to the right hand side.

<a id='datatype'></a>
## Manipulating Data Types
([Back to Table of Contents](#toc))

In [19]:
iris['species'].dtypes

dtype('O')

In [20]:
iris['species'] = iris['species'].astype('category') 

# note we had to set the column equal to the transformation
# if we had left out the left hand side, the original series would not be transformed

iris['species'].dtypes

category

<a id='gen'></a>
## Generating Variables
([Back to Table of Contents](#toc))

In [21]:
# Based on a combination of other columns
iris['petal_area'] = np.pi*iris['petal_length']*iris['petal_width']
iris.head()

    sepal_length  sepal_width  petal_length  petal_width species  petal_area
13           4.3          3.0           1.1          0.1  setosa    0.345575
42           4.4          3.2           1.3          0.2  setosa    0.816814
38           4.4          3.0           1.3          0.2  setosa    0.816814
8            4.4          2.9           1.4          0.2  setosa    0.879646
41           4.5          2.3           1.3          0.3  setosa    1.225221

In [22]:
# Creating a dummy variable based on a condition
iris['bigpetal'] = np.where((iris['petal_length'] >= 4) & (iris['petal_width'] >= 2), 1, 0)
iris.head()

,sepal_length,sepal_width,petal_length,petal_width,species,petal_area,bigpetal
13,4.3,3.0,1.1,0.1,setosa,0.345575,0
42,4.4,3.2,1.3,0.2,setosa,0.816814,0
38,4.4,3.0,1.3,0.2,setosa,0.816814,0
8,4.4,2.9,1.4,0.2,setosa,0.879646,0
41,4.5,2.3,1.3,0.3,setosa,1.225221,0

In [23]:
# Creating a categorical variable
iris['petallength_cat'] = pd.cut(iris['petal_length'], [1, 2, 3, 4, 5, 6, 7], labels=["Very Small", "Small", "Medium", "Large", "Very Large", "Enormous"])

<a id='tab'></a>
## Summary Statistics and Tabulation
([Back to Table of Contents](#toc))

In [24]:
# Summary statistics for each columns
iris.describe()

,sepal_length,sepal_width,petal_length,petal_width,petal_area,bigpetal
count,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333,18.202597,0.193333
std,0.828066,0.435866,1.765298,0.762238,14.804410,0.396235
min,4.300000,2.000000,1.000000,0.100000,0.345575,0.000000
25%,5.100000,2.800000,1.600000,0.300000,1.319469,0.000000
50%,5.800000,3.000000,4.350000,1.300000,17.640043,0.000000
75%,6.400000,3.300000,5.100000,1.800000,30.442033,0.000000
max,7.900000,4.400000,6.900000,2.500000,49.857075,1.000000

In [25]:
# Specific summary statistic for a specific column
print(iris['sepal_length'].mean())

5.843333333333335

By "tabulating" data, we usually mean that we are performing some aggregation over some non-continuous variable. E.g., we might want to get the count of observations by species.

When we cross-tabuate, we do the same, but compare one categorical variable against another.

Finally, one variation of tabulation is to calculate an aggregate statistic for one variable, but *group* by another.

There are multiple ways of achieving each of these three manipulations in pandas. Most popularly, you can use the methods **pivot_table**, **crosstab**, or **groupby**.

In [26]:
# Tabulate species
iris.groupby('species')['petal_length'].count()

species
setosa        50
versicolor    50
virginica     50
Name: petal_length, dtype: int64

In [27]:
# Simple cross-tab
pd.crosstab(iris['species'], iris['petallength_cat'])

petallength_cat  Very Small  Small  Medium  Large  Very Large  Enormous
species
setosa                   49      0       0      0           0         0
versicolor                0      1      15     33           1         0
virginica                 0      0       0      9          32         9

In [28]:
# Calculate each cell as a percentage of its column
#pd.crosstab(iris['species'], iris['petallength_cat']).apply(lambda x: x/x.sum(), axis=0) # earlier versions of pandas
pd.crosstab(iris['species'], iris['petallength_cat'], normalize='columns')

petallength_cat  Very Small  Small  Medium     Large  Very Large  Enormous
species
setosa                  1.0    0.0     0.0  0.000000    0.000000       0.0
versicolor              0.0    1.0     1.0  0.785714    0.030303       0.0
virginica               0.0    0.0     0.0  0.214286    0.969697       1.0

In [29]:
# Calculate each cell as a percentage of its row
# pd.crosstab(iris['species'], iris['petallength_cat']).apply(lambda x: x/x.sum(), axis=1) # earlier versions of pandas
pd.crosstab(iris['species'], iris['petallength_cat'], normalize='index')

petallength_cat  Very Small  Small  Medium  Large  Very Large  Enormous
species
setosa                  1.0   0.00     0.0   0.00        0.00      0.00
versicolor              0.0   0.02     0.3   0.66        0.02      0.00
virginica               0.0   0.00     0.0   0.18        0.64      0.18

In [31]:
# Get mean by categorical variables (can substitute max(), mean(), etc)
iris.groupby('petallength_cat')['petal_length'].min()

petallength_cat
Very Small    1.1
Small         3.0
Medium        3.3
Large         4.1
Very Large    5.1
Enormous      6.1
Name: petal_length, dtype: float64

In [32]:
# Get max by categorical variables
iris.groupby('species')['petal_length'].max()

species
setosa        1.9
versicolor    5.1
virginica     6.9
Name: petal_length, dtype: float64

<a id='concat'></a>
## Concatenating Dataframes
([Back to Table of Contents](#toc))

### Vertical concatenation (appending)

Say we had two dataframes with identical columns. We might want to *vertically concatenate* them; that is, we might want to paste one on top of the other to get a single dataset. Consider:

In [33]:
# Create three datasets, one for each species
setosa = iris[iris['species']=="setosa"]
versicolor = iris[iris['species']=="versicolor"]
virginica = iris[iris['species']=="virginica"]

In [34]:
setosa.head()

,sepal_length,sepal_width,petal_length,petal_width,species,petal_area,bigpetal,petallength_cat
13,4.3,3.0,1.1,0.1,setosa,0.345575,0,Very Small
42,4.4,3.2,1.3,0.2,setosa,0.816814,0,Very Small
38,4.4,3.0,1.3,0.2,setosa,0.816814,0,Very Small
8,4.4,2.9,1.4,0.2,setosa,0.879646,0,Very Small
41,4.5,2.3,1.3,0.3,setosa,1.225221,0,Very Small

In [35]:
df = pd.concat([setosa, versicolor, virginica])
df

,sepal_length,sepal_width,petal_length,petal_width,species,petal_area,bigpetal,petallength_cat
13,4.3,3.0,1.1,0.1,setosa,0.345575,0,Very Small
42,4.4,3.2,1.3,0.2,setosa,0.816814,0,Very Small
38,4.4,3.0,1.3,0.2,setosa,0.816814,0,Very Small
8,4.4,2.9,1.4,0.2,setosa,0.879646,0,Very Small
41,4.5,2.3,1.3,0.3,setosa,1.225221,0,Very Small
22,4.6,3.6,1.0,0.2,setosa,0.628319,0,NaN
3,4.6,3.1,1.5,0.2,setosa,0.942478,0,Very Small
6,4.6,3.4,1.4,0.3,setosa,1.319469,0,Very Small
47,4.6,3.2,1.4,0.2,setosa,0.879646,0,Very Small
29,4.7,3.2,1.6,0.2,setosa,1.005310,0,Very Small
2,4.7,3.2,1.3,0.2,setosa,0.816814,0,Very Small
12,4.8,3.0,1.4,0.1,setosa,0.439823,0,Very Small
45,4.8,3.0,1.4,0.3,setosa,1.319469,0,Very Small
24,4.8,3.4,1.9,0.2,setosa,1.193805,0,Very Small
11,4.8,3.4,1.6,0.2,setosa,1.005310,0,Very Small
30,4.8,3.1,1.6,0.2,setosa,1.005310,0,Very Small
1,4.9,3.0,1.4,0.2,setosa,0.879646,0,Very Small
37,4.9,3.6,1.4,0.1,setosa,0.439823,0,Very Small
9,4.9,3.1,1.5,0.1,setosa,0.471239,0,Very Small
34,4.9,3.1,1.5,0.2,setosa,0.942478,0,Very Small
40,5.0,3.5,1.3,0.3,setosa,1.225221,0,Very Small
26,5.0,3.4,1.6,0.4,setosa,2.010619,0,Very Small
49,5.0,3.3,1.4,0.2,setosa,0.879646,0,Very Small
35,5.0,3.2,1.2,0.2,setosa,0.753982,0,Very Small
43,5.0,3.5,1.6,0.6,setosa,3.015929,0,Very Small
7,5.0,3.4,1.5,0.2,setosa,0.942478,0,Very Small
4,5.0,3.6,1.4,0.2,setosa,0.879646,0,Very Small
25,5.0,3.0,1.6,0.2,setosa,1.005310,0,Very Small
23,5.1,3.3,1.7,0.5,setosa,2.670354,0,Very Small
19,5.1,3.8,1.5,0.3,setosa,1.413717,0,Very Small
...,...,...,...,...,...,...,...,...
111,6.4,2.7,5.3,1.9,virginica,31.635838,0,Very Large
128,6.4,2.8,5.6,2.1,virginica,36.945130,1,Very Large
137,6.4,3.1,5.5,1.8,virginica,31.101767,0,Very Large
132,6.4,2.8,5.6,2.2,virginica,38.704421,1,Very Large
104,6.5,3.0,5.8,2.2,virginica,40.086722,1,Very Large
116,6.5,3.0,5.5,1.8,virginica,31.101767,0,Very Large
147,6.5,3.0,5.2,2.0,virginica,32.672564,1,Very Large
110,6.5,3.2,5.1,2.0,virginica,32.044245,1,Very Large
145,6.7,3.0,5.2,2.3,virginica,37.573448,1,Very Large
144,6.7,3.3,5.7,2.5,virginica,44.767695,1,Very Large
108,6.7,2.5,5.8,1.8,virginica,32.798227,0,Very Large
140,6.7,3.1,5.6,2.4,virginica,42.223005,1,Very Large
124,6.7,3.3,5.7,2.1,virginica,37.604864,1,Very Large
112,6.8,3.0,5.5,2.1,virginica,36.285395,1,Very Large
143,6.8,3.2,5.9,2.3,virginica,42.631412,1,Very Large
139,6.9,3.1,5.4,2.1,virginica,35.625661,1,Very Large
141,6.9,3.1,5.1,2.3,virginica,36.850882,1,Very Large
120,6.9,3.2,5.7,2.3,virginica,41.186280,1,Very Large
102,7.1,3.0,5.9,2.1,virginica,38.924333,1,Very Large
125,7.2,3.2,6.0,1.8,virginica,33.929201,0,Very Large
129,7.2,3.0,5.8,1.6,virginica,29.153980,0,Very Large
109,7.2,3.6,6.1,2.5,virginica,47.909288,1,Enormous
107,7.3,2.9,6.3,1.8,virginica,35.625661,0,Enormous
130,7.4,2.8,6.1,1.9,virginica,36.411059,0,Enormous
105,7.6,3.0,6.6,2.1,virginica,43.542474,1,Enormous
117,7.7,3.8,6.7,2.2,virginica,46.307076,1,Enormous
135,7.7,3.0,6.1,2.3,virginica,44.076545,1,Enormous
122,7.7,2.8,6.7,2.0,virginica,42.097342,1,Enormous
118,7.7,2.6,6.9,2.3,virginica,49.857075,1,Enormous
131,7.9,3.8,6.4,2.0,virginica,40.212386,1,Enormous

### Merging (horizontal concatenation)

Say we had two dataframes with *different* columns, but the observations in both were the same (e.g., each row represented each state in the United States, or a different flower). We might want to merge these together.

To do this, we need a unique key (a single column, or multiple columns) that identifies each observation in each dataframes. Furthermore, this key must be shared across both dataframes.

With the iris dataset, first observe that the index can represent a unique key. Now, let's move forward keeping this bit of information in mind.

In [38]:
# Create two different dataframes, each with mutually exclusive columns
petal = iris[['petal_length', 'petal_width']]
sepal = iris[['sepal_length', 'sepal_width']]

In [37]:
# Merge together on the index
pd.merge(petal, sepal, left_index = True, right_index=True)

     petal_length  petal_width  sepal_length  sepal_width
13            1.1          0.1           4.3          3.0
42            1.3          0.2           4.4          3.2
38            1.3          0.2           4.4          3.0
8             1.4          0.2           4.4          2.9
41            1.3          0.3           4.5          2.3
22            1.0          0.2           4.6          3.6
3             1.5          0.2           4.6          3.1
6             1.4          0.3           4.6          3.4
47            1.4          0.2           4.6          3.2
29            1.6          0.2           4.7          3.2
2             1.3          0.2           4.7          3.2
12            1.4          0.1           4.8          3.0
45            1.4          0.3           4.8          3.0
24            1.9          0.2           4.8          3.4
11            1.6          0.2           4.8          3.4
30            1.6          0.2           4.8          3.1
1             1.4          0.2           4.9          3.0
37            1.4          0.1           4.9          3.6
9             1.5          0.1           4.9          3.1
106           4.5          1.7           4.9          2.5
57            3.3          1.0           4.9          2.4
34            1.5          0.2           4.9          3.1
40            1.3          0.3           5.0          3.5
26            1.6          0.4           5.0          3.4
49            1.4          0.2           5.0          3.3
35            1.2          0.2           5.0          3.2
43            1.6          0.6           5.0          3.5
60            3.5          1.0           5.0          2.0
7             1.5          0.2           5.0          3.4
93            3.3          1.0           5.0          2.3
..            ...          ...           ...          ...
75            4.4          1.4           6.6          3.0
58            4.6          1.3           6.6          2.9
145           5.2          2.3           6.7          3.0
144           5.7          2.5           6.7          3.3
65            4.4          1.4           6.7          3.1
86            4.7          1.5           6.7          3.1
108           5.8          1.8           6.7          2.5
140           5.6          2.4           6.7          3.1
124           5.7          2.1           6.7          3.3
77            5.0          1.7           6.7          3.0
112           5.5          2.1           6.8          3.0
143           5.9          2.3           6.8          3.2
76            4.8          1.4           6.8          2.8
139           5.4          2.1           6.9          3.1
141           5.1          2.3           6.9          3.1
52            4.9          1.5           6.9          3.1
120           5.7          2.3           6.9          3.2
50            4.7          1.4           7.0          3.2
102           5.9          2.1           7.1          3.0
125           6.0          1.8           7.2          3.2
129           5.8          1.6           7.2          3.0
109           6.1          2.5           7.2          3.6
107           6.3          1.8           7.3          2.9
130           6.1          1.9           7.4          2.8
105           6.6          2.1           7.6          3.0
117           6.7          2.2           7.7          3.8
135           6.1          2.3           7.7          3.0
122           6.7          2.0           7.7          2.8
118           6.9          2.3           7.7          2.6
131           6.4          2.0           7.9          3.8

[150 rows x 4 columns]

## Anything else?

As I mentioned, this is supposed to be a brief introduction into pandas. Here, I wanted to take a relatively simple dataset and work through the basics of any data analysis. As a result, there is a lot I missed:

*Retrieving and Importing Data*  
Python's strength relative to R or Stata is that you can use it to grab a variety of data existing in any form and work to convert it to a rectangular form you can analyze using pandas. The package Beautiful Soup is a great place to start if you'd like to scrape data from the web.

There are also a number of pandas methods that can help you import data that already exist in some rectangular frame. **read_csv** is probably the right place to start.

Finally, I completely ignored the fact that you can have multiple indices or column headers. This is extremely powerful and has saved me a ton of pain when dealing with tables I scrape from the internet. This is certainly worth looking into!

*Tidying Data*  
Perhaps most criminally, I didn't discuss how to deal with missings. You should start your self-directed learning by looking into this. You may want to start with **fillna** and **dropna**.

I also completely ignored how to reshape data (e.g., converting data from long to wide). Appropriately, you may want to look into pandas' **reshape** method.

*Visualization*  
Visualizing data is its own beast. I couldn't even get into the basics and still make this a manageable tutorial. Start with **matplotlib** and move on to **seaborn**.

# END OF FILE